#!/bin/bash

url="http://127.0.0.1:8001/communication"
for i in `seq 1 100`;
do
    content="$(curl -X POST "$url" -d '{"provider":"google"}')"
    echo "$content" >> output.txt
done

for i in `seq 1 200`;
do
    content="$(curl -X POST "$url" -d '{"provider":"sumup"}')"
    echo "$content" >> output.txt
done

for i in `seq 1 100`;
do
    content="$(curl -X POST "$url" -d '{"provider":"google"}')"
    echo "$content" >> output.txt
done

reports="$(curl -X GET "http://127.0.0.1:8001/stats" )"
echo "=====================" >> output.txt
echo "$reports" >> output.txt
